-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ModelWithApproximation_20210821T210314460\ModelWithApproximation_20210821T210314460.vhd
-- Created: 2021-08-21 21:51:33
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ModelWithApproximation_20210821T210314460
-- Source Path: ModelWithApproximation_20210821T210314460
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ModelWithApproximation_20210821T210314460 IS
END ModelWithApproximation_20210821T210314460;


ARCHITECTURE rtl OF ModelWithApproximation_20210821T210314460 IS

BEGIN
  -- Open scope to see simulation results


END rtl;

